/*auto complete resource http://codehotfix.com/autocomplete-textbox-using-jqueryjson-database */
/*bootstrap templete resources https://www.mockplus.com/blog/post/bootstrap-form-template
https://codepen.io/juff03/pen/OXaXRG */
var data = [
  "BIOL  1010  General Biology LS   ",
  "BIOL  1015  General Biology Lab LB  ",
  "BIOL  1050  Human Biology LS ",
  "BIOL  1055  Human Biology Lab LB ",
  "BIOL  1420  Environmental Biology LS  ",
  "BIOL  1425  Environmental Biology Lab LB ",
  "BIOL  1450  Human Dynamics - LS  ",
  "BIOL  1455  Human Dynamics Lab LB   ",
  "BIOL  1460  Bird, Biology, & You ",
  "BIOL  1465  Bird, Biology Lab    ",
  "BIOL  1610  Biology I LS  ",
  "BIOL  1615  Biology I Laboratory LB ",
  "BIOL  1620  Biology II LS ",
  "BIOL  1625  Biology II Laboratory LB  ",
  "BIOL  1997  Biol/Health Sci. Intern. I   ",
  "BIOL  1998  Cooperative Education 1st yr ",
  "BIOL  2030  Introductory Genetics   ",
  "BIOL  2035  Introductory Genetics Lab LB ",
  "BIOL  2060  Introductory Microbiology LS ",
  "BIOL  2065  Intro Microbiology Lab LB ",
  "BIOL  2120  Rural Health Scholars   ",
  "BIOL  2122  Analysis/Reading in Healthcare  ",
  "BIOL  2200  General Microbiology LS ",
  "BIOL  2205  General Microbiology Lab LB  ",
  "BIOL  2220  Gen Ecology for Life Sc Majors  ",
  "BIOL  2225  Gen Ecology Life Sci Maj Lab ",
  "BIOL  2320  Human Anatomy LS ",
  "BIOL  2325  Human Anatomy Lab LB ",
  "BIOL  2420  Human Physiology ",
  "BIOL  2425  Human Physiology Lab LB ",
  "BIOL  2450  Undergraduate Teaching in BIOL  ",
  "BIOL  2580  Intro to Soil Science   ",
  "BIOL  2585  Intro to Soil Science Lab ",
  "BIOL  2650  Pathophysiology  ",
  "BIOL  2915  Undergraduate Research  ",
  "BIOL  2925  Undergraduate Research  ",
  "HESC  1500  EMT-Emergency Medical Tech   ",
  "CS  1400  Programming Fundamentals  ",
  "CS  1405  Programming Fundamentals Lab   ",
  "CS  1410  Object-Oriented Programming ",
  "CS  1415  Object-Oriented Program Lab ",
  "CS  1810  Web Development I  ",
  "CS  1820  Web Development II ",
  "CS  2420  Data Structures & Algorithms   ",
  "CS  2450  Intro to Software Engineering  ",
  "CS  2700  Digital Circuits   ",
  "CS  2810  Computer Organiz/Architecture  ",
  "CS  2830  Web Development III    ",
  "CS  2860  Operating Systems  ",
  "CIS  1060  IT Project Management ",
  "CIS  1125  IT Essentials  ",
  "CIS  1140  Network Essentials    ",
  "CIS  1155  BICSI Optical Fiber Structured   ",
  "CIS  1200  Introduction to Networks ",
  "CIS  1205  Routing & Switching Essentials   ",
  "CIS  1310  Network Security Fundamentals ",
  "CIS  1620  Linux Fundamentals    ",
  "CIS  1715  Applied Technical Math   ",
  "CIS  1930  Leadership/Professional Dev 1 ",
  "CIS  2200  Scaling Networks in the Enterp   ",
  "CIS  2205  Wide Area Networking Fundament   ",
  "CIS  2210  Cisco ROUTE: Implement IP Rout   ",
  "CIS  2215  Cisco SWITCH:Implement IP Swit   ",
  "CIS  2220  Cisco TSHOOT: Maintain/Trouble   ",
  "CIS  2250  Cisco VOIP Networking Fundamen   ",
  "CIS  2300  Cisco Wireless Networking Fund   ",
  "CIS  2400  Advanced Windows Server Config   ",
  "CIS  2930  Leadership/Professional Dev 2 ",
  "ENGL  2250  Intro to Creative Writing ",
  "ENGL  2260  Fiction Writing  ",
  "ENGL  2270  Writing Poetry   ",
  "ENGL  2300  Intro to Shakespeare HU ",
  "ENGL  2330  Children's Literature   ",
  "ENGL  2360  Contemporary World Lit HU ",
  "ENGL  2410  Literature of American West HU  ",
  "ENGL  2420  Literature Of The Outdoors HU   ",
  "ENGL  2430  Gothic & Supernatural Lit HU ",
  "ENGL  2450  Introduction to Gender Studies  ",
  "ENGL  2460  African-American Literature HU  ",
  "ENGL  2510  Masterpieces Of Amer Lit HU  ",
  "ENGL  2520  Masterpieces of Amer Lit HU  ",
  "ENGL  2600  Intr to Critical Lit/Theory  ",
  "ENGL  2610  Masterpieces/ British Lit I HU  ",
  "ENGL  2620  Masterpieces/British Lit II HU  ",
  "ENGL  2650  Language In Society HU  ",
  "ENGL  2660  Intro to Language Systems HU ",
  "ENGL  2800  Special Projects ",
  "ENGL  2950  Meth. Prac. in Tutor Writers ",
  "ENGL  3260  Technical Communication ",
  "PHIL  1000  Intro to Philosophy HU  ",
  "PHIL  1050  Ethics & Bus. Leadership HU  ",
  "PHIL  2050  Ethics and Values HU ",
  "PHIL  2600  World Religion HU    ",
  "ENGR  1000  Intro to Engineering ",
  "ENGR  1300  Engr Graphics & Design  ",
  "ENGR  1997  Engineering Internship I  ",
  "ENGR  2010  Statics ",
  "ENGR  2030  Dynamics   ",
  "ENGR  2140  Strength of Materials   ",
  "ENGR  2160  Materials Science    ",
  "ENGR  2240  Survey & Global Positioning  ",
  "ENGR  2250  Analog Circuits  ",
  "ENGR  2255  Analog Circuits Laboratory   ",
  "ENGR  2290  Analog Circuits II   ",
  "ENGR  2295  Analog Circuits II Lab  ",
  "ENGR  2300  Engineering Thermodynamics   ",
  "ENGR  2450  Numerical Methods    ",
  "ENGR  2700  Digital Circuits ",
  "ENGR  2705  Digital Circuits Lab ",
  "ENGR  2850  Special Topics	 "];

$(function() {
    $("#courseName").autocomplete({
      source: data,
      scroll: true
    });
  });
